language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm clean
  - npm run build
deploy:
  verbose: true
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  github_token: $github_token
  on:
branch: master
